site_name: Tektite
repo_url: https://github.com/spirit-labs/tektite/
theme:
  name: material
  palette:
    accent: indigo
nav:
  - Home: 'index.md'
  - Installation: 'installation.md'
  - Getting started: 'getting_started.md'
  - Concepts: 'conceptual_model.md'
  - Running servers: 'running_servers.md'
  - The command line: 'cli.md'
  - Topics: 'topics.md'
  - Projections: 'projections.md'
  - Filters: 'filtering.md'
  - Persistence: 'persistence.md'
  - Aggregations: 'aggregating.md'
  - Watermarks: 'watermarks.md'
  - Joins: 'joins.md'
  - Unions: 'union.md'
  - Queries: 'queries.md'
  - Bridges: 'bridging.md'
  - Partitions: 'partitions.md'
  - Expressions: 'expressions.md'
  - Functions: 'functions.md'
  - Back-filling: 'backfill.md'
  - Object stores: 'object_stores.md'
  - HTTP API: 'http_api.md'
  - WebAssembly: 'wasm.md'
  - Admin Console: 'admin_console.md'
  - Configuration: 'configuration.md'
markdown_extensions:
  - tables
